// PDF Report Generation Service
// Creates monthly portfolio performance reports

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { PerformanceAttribution } from './advanced'

export type PortfolioReportData = {
    portfolioName: string
    period: { start: Date; end: Date }
    totalValue: number
    totalReturn: number
    returnPercent: number
    bestPerformer: { name: string; return: number }
    worstPerformer: { name: string; return: number }
    attribution: PerformanceAttribution[]
    sharpeRatio: number
    maxDrawdown: number
    cardCount: number
}

// Generate monthly portfolio PDF report
export function generatePortfolioReport(data: PortfolioReportData): jsPDF {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()

    // Header
    doc.setFontSize(20)
    doc.setTextColor(41, 41, 41)
    doc.text('Altum Analytics', 14, 15)

    doc.setFontSize(16)
    doc.text('Portfolio Performance Report', 14, 25)

    doc.setFontSize(10)
    doc.setTextColor(100, 100, 100)
    doc.text(data.portfolioName, 14, 32)
    doc.text(
        `${formatDate(data.period.start)} - ${formatDate(data.period.end)}`,
        14,
        38
    )

    // Summary section
    let yPos = 50
    doc.setFontSize(14)
    doc.setTextColor(41, 41, 41)
    doc.text('Portfolio Summary', 14, yPos)

    yPos += 8
    doc.setFontSize(10)
    doc.text(`Total Value: € ${formatNumber(data.totalValue)}`, 20, yPos)
    yPos += 6
    doc.text(`Total Return: € ${formatNumber(data.totalReturn)} (${data.returnPercent.toFixed(2)}%)`, 20, yPos)
    yPos += 6
    doc.text(`Number of Cards: ${data.cardCount}`, 20, yPos)

    yPos += 10
    doc.setFontSize(14)
    doc.text('Risk Metrics', 14, yPos)

    yPos += 8
    doc.setFontSize(10)
    doc.text(`Sharpe Ratio: ${data.sharpeRatio.toFixed(2)}`, 20, yPos)
    yPos += 6
    doc.text(`Maximum Drawdown: ${data.maxDrawdown.toFixed(2)}%`, 20, yPos)

    // Best/Worst performers
    yPos += 10
    doc.setFontSize(14)
    doc.text('Top Performers', 14, yPos)

    yPos += 8
    doc.setFontSize(10)
    doc.setTextColor(34, 139, 34) // Green
    doc.text(`Best: ${data.bestPerformer.name} (+${data.bestPerformer.return.toFixed(2)}%)`, 20, yPos)

    yPos += 6
    doc.setTextColor(220, 20, 60) // Red
    doc.text(`Worst: ${data.worstPerformer.name} (${data.worstPerformer.return.toFixed(2)}%)`, 20, yPos)

    // Performance Attribution Table
    yPos += 12
    doc.setTextColor(41, 41, 41)
    doc.setFontSize(14)
    doc.text('Performance Attribution', 14, yPos)

    yPos += 6

    const tableData = data.attribution.slice(0, 10).map(attr => [
        attr.cardName,
        `${attr.weight.toFixed(2)}%`,
        `${attr.returns.toFixed(2)}%`,
        `${attr.contribution.toFixed(2)}%`
    ])

    autoTable(doc, {
        startY: yPos,
        head: [['Card', 'Weight', 'Return', 'Contribution']],
        body: tableData,
        theme: 'grid',
        headStyles: {
            fillColor: [41, 41, 41],
            textColor: [255, 255, 255],
            fontSize: 10
        },
        bodyStyles: {
            fontSize: 9
        },
        columnStyles: {
            0: { cellWidth: 80 },
            1: { cellWidth: 30, halign: 'right' },
            2: { cellWidth: 30, halign: 'right' },
            3: { cellWidth: 35, halign: 'right' }
        }
    })

    // Footer
    const pageCount = doc.internal.pages.length - 1
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i)
        doc.setFontSize(8)
        doc.setTextColor(150, 150, 150)
        doc.text(
            `Generated by Altum Analytics - ${new Date().toLocaleDateString()}`,
            14,
            doc.internal.pageSize.getHeight() - 10
        )
        doc.text(
            `Page ${i} of ${pageCount}`,
            pageWidth - 30,
            doc.internal.pageSize.getHeight() - 10
        )
    }

    return doc
}

// Helper: Format date
function formatDate(date: Date): string {
    return date.toLocaleDateString('fr-FR', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    })
}

// Helper: Format number with thousands separator
function formatNumber(num: number): string {
    return new Intl.NumberFormat('fr-FR', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
    }).format(num)
}

// Export report as blob for download
export function downloadReport(doc: jsPDF, filename: string): void {
    doc.save(filename)
}

// Get report as base64 string (for API)
export function getReportBase64(doc: jsPDF): string {
    return doc.output('datauristring')
}
